version: "3"
services:
  web:
    build: . # imageがなかったらdockerfileからimageをbuildし引っ張ってくる
    command: "/app/docker-entrypoint.sh"
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    volumes:
      - .:/app
    depends_on: # 依存関係。依存あるものより先にbuildされなくなる
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql #コンテナが終了してもデータベースにデータが保持されるようにしておける
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume: # localに存在しないため、無理やり作成した。
